/* SPDX-License-Identifier: GPL-2.0 or BSD-3-Clause */
/*
 * Copyright(c) 2025 Cornelis Networks, Inc.
 * Copyright(c) 2015 - 2018 Intel Corporation.
 */

#ifndef _HFI1_SDMA_DEFS_H
#define _HFI1_SMDA_DEFS_H

/* Hardware limit */
#define MAX_DESC 64
/* Hardware limit for SDMA packet size */
#define MAX_SDMA_PKT_SIZE ((16 * 1024) - 1)

#define SDMA_MAP_NONE          0
#define SDMA_MAP_SINGLE        1
#define SDMA_MAP_PAGE          2

#define SDMA_MAP_BITS          2
#define SDMA_MAP_MASK          ((1ull << SDMA_MAP_BITS) - 1)

#define SDMA_AHG_VALUE_MASK          0xffff
#define SDMA_AHG_VALUE_SHIFT         0
#define SDMA_AHG_INDEX_MASK          0xf
#define SDMA_AHG_INDEX_SHIFT         16
#define SDMA_AHG_FIELD_LEN_MASK      0xf
#define SDMA_AHG_FIELD_LEN_SHIFT     20
#define SDMA_AHG_FIELD_START_MASK    0x1f
#define SDMA_AHG_FIELD_START_SHIFT   24
#define SDMA_AHG_UPDATE_ENABLE_MASK  0x1
#define SDMA_AHG_UPDATE_ENABLE_SHIFT 31

/* AHG modes */

/*
 * Be aware the ordering and values
 * for SDMA_AHG_APPLY_UPDATE[123]
 * are assumed in generating a skip
 * count in submit_tx() in sdma.c
 */
#define SDMA_AHG_NO_AHG              0
#define SDMA_AHG_COPY                1
#define SDMA_AHG_APPLY_UPDATE1       2
#define SDMA_AHG_APPLY_UPDATE2       3
#define SDMA_AHG_APPLY_UPDATE3       4

/*
 * Bits defined in the send DMA descriptor.
 */
/* WFR SDMA header fields */
#define WFR_SDMA_DESC0_FIRST_DESC_FLAG      BIT_ULL(63)
#define WFR_SDMA_DESC0_LAST_DESC_FLAG       BIT_ULL(62)
#define WFR_SDMA_DESC0_BYTE_COUNT_SHIFT     48
#define WFR_SDMA_DESC0_BYTE_COUNT_WIDTH     14
#define WFR_SDMA_DESC0_BYTE_COUNT_MASK \
	((1ULL << WFR_SDMA_DESC0_BYTE_COUNT_WIDTH) - 1)
#define WFR_SDMA_DESC0_BYTE_COUNT_SMASK \
	(WFR_SDMA_DESC0_BYTE_COUNT_MASK << WFR_SDMA_DESC0_BYTE_COUNT_SHIFT)
#define WFR_SDMA_DESC0_PHY_ADDR_SHIFT       0
#define WFR_SDMA_DESC0_PHY_ADDR_WIDTH       48
#define WFR_SDMA_DESC0_PHY_ADDR_MASK \
	((1ULL << WFR_SDMA_DESC0_PHY_ADDR_WIDTH) - 1)
#define WFR_SDMA_DESC0_PHY_ADDR_SMASK \
	(WFR_SDMA_DESC0_PHY_ADDR_MASK << WFR_SDMA_DESC0_PHY_ADDR_SHIFT)

/* JKR SDMA header fields */
#define JKR_SDMA_DESC0_PHY_ADDR_SHIFT       0
#define JKR_SDMA_DESC0_PHY_ADDR_WIDTH       58
#define JKR_SDMA_DESC0_PHY_ADDR_MASK \
	((1ULL << JKR_SDMA_DESC0_PHY_ADDR_WIDTH) - 1)
#define JKR_SDMA_DESC0_PHY_ADDR_SMASK \
	(JKR_SDMA_DESC0_PHY_ADDR_MASK << JKR_SDMA_DESC0_PHY_ADDR_SHIFT)

#define JKR_SDMA_DESC1_FIRST_DESC_FLAG      BIT_ULL(31)
#define JKR_SDMA_DESC1_LAST_DESC_FLAG       BIT_ULL(30)
#define JKR_SDMA_DESC1_BYTE_COUNT_SHIFT     16
#define JKR_SDMA_DESC1_BYTE_COUNT_WIDTH     14
#define JKR_SDMA_DESC1_BYTE_COUNT_MASK \
	((1ULL << JKR_SDMA_DESC1_BYTE_COUNT_WIDTH) - 1)
#define JKR_SDMA_DESC1_BYTE_COUNT_SMASK \
	(JKR_SDMA_DESC1_BYTE_COUNT_MASK << JKR_SDMA_DESC1_BYTE_COUNT_SHIFT)

/* common SDMA header fields */
#define SDMA_DESC1_HEADER_UPDATE1_SHIFT 32
#define SDMA_DESC1_HEADER_UPDATE1_WIDTH 32
#define SDMA_DESC1_HEADER_UPDATE1_MASK \
	((1ULL << SDMA_DESC1_HEADER_UPDATE1_WIDTH) - 1)
#define SDMA_DESC1_HEADER_UPDATE1_SMASK \
	(SDMA_DESC1_HEADER_UPDATE1_MASK << SDMA_DESC1_HEADER_UPDATE1_SHIFT)
#define SDMA_DESC1_HEADER_MODE_SHIFT    13
#define SDMA_DESC1_HEADER_MODE_WIDTH    3
#define SDMA_DESC1_HEADER_MODE_MASK \
	((1ULL << SDMA_DESC1_HEADER_MODE_WIDTH) - 1)
#define SDMA_DESC1_HEADER_MODE_SMASK \
	(SDMA_DESC1_HEADER_MODE_MASK << SDMA_DESC1_HEADER_MODE_SHIFT)
#define SDMA_DESC1_HEADER_INDEX_SHIFT   8
#define SDMA_DESC1_HEADER_INDEX_WIDTH   5
#define SDMA_DESC1_HEADER_INDEX_MASK \
	((1ULL << SDMA_DESC1_HEADER_INDEX_WIDTH) - 1)
#define SDMA_DESC1_HEADER_INDEX_SMASK \
	(SDMA_DESC1_HEADER_INDEX_MASK << SDMA_DESC1_HEADER_INDEX_SHIFT)
#define SDMA_DESC1_HEADER_DWS_SHIFT     4
#define SDMA_DESC1_HEADER_DWS_WIDTH     4
#define SDMA_DESC1_HEADER_DWS_MASK \
	((1ULL << SDMA_DESC1_HEADER_DWS_WIDTH) - 1)
#define SDMA_DESC1_HEADER_DWS_SMASK \
	(SDMA_DESC1_HEADER_DWS_MASK << SDMA_DESC1_HEADER_DWS_SHIFT)
#define SDMA_DESC1_GENERATION_SHIFT     2
#define SDMA_DESC1_GENERATION_WIDTH     2
#define SDMA_DESC1_GENERATION_MASK \
	((1ULL << SDMA_DESC1_GENERATION_WIDTH) - 1)
#define SDMA_DESC1_GENERATION_SMASK \
	(SDMA_DESC1_GENERATION_MASK << SDMA_DESC1_GENERATION_SHIFT)
#define SDMA_DESC1_INT_REQ_FLAG         BIT_ULL(1)
#define SDMA_DESC1_HEAD_TO_HOST_FLAG    BIT_ULL(0)
#endif /* _HFI1_SDMA_H */
