PACKAGE_NAME="@@PACKAGE@@"
PACKAGE_VERSION="@@VERSION@@"
AUTOINSTALL="yes"
#module_build_dir="$(mktemp -ut opa.XXXXXXXX)"
PRE_BUILD="hdrinst $kernelver"
POST_REMOVE="hdrrest $kernelver"
# not all OS supports weak module updates
NO_WEAK_MODULES="yes"

BUILT_MODULE_NAME[0]="rdmavt"
BUILT_MODULE_LOCATION[0]="rdmavt/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/infiniband/sw/rdmavt"

BUILT_MODULE_NAME[1]="hfi1"
BUILT_MODULE_LOCATION[1]="hfi1/"
DEST_MODULE_LOCATION[1]="/kernel/drivers/infiniband/hw/hfi1"

num_cpu_cores()
{
	if [ -x /usr/bin/nproc ]; then
		nproc
	else
		echo "1"
	fi
}

MAKE[0]="'make' -j $(num_cpu_cores) KDIR=$kernel_source_dir \
	CONFIG_INFINIBAND_RDMAVT=m DISTROFLAG=U2404 \
	@@GPUOPTS@@"

BUILD_EXCLUSIVE_KERNEL="6.8.0-*"
